import { validateLevel, type LevelData } from '@/game/level';
import i01 from './levels/i01.json';
import i02 from './levels/i02.json';
import i03 from './levels/i03.json';
import i04 from './levels/i04.json';
import i05 from './levels/i05.json';
import i06 from './levels/i06.json';
import i07 from './levels/i07.json';
import d01 from './levels/d01.json';
import d02 from './levels/d02.json';
import d03 from './levels/d03.json';
import d04 from './levels/d04.json';
import d05 from './levels/d05.json';
import d06 from './levels/d06.json';
import d07 from './levels/d07.json';
import d08 from './levels/d08.json';
import d09 from './levels/d09.json';
import d10 from './levels/d10.json';
import d11 from './levels/d11.json';
import d12 from './levels/d12.json';
import t12 from './levels/t12.json';
import d13 from './levels/d13.json';
import d14 from './levels/d14.json';
import d15 from './levels/d15.json';
import d16 from './levels/d16.json';
import d17 from './levels/d17.json';
import d18 from './levels/d18.json';
import d19 from './levels/d19.json';
import d20 from './levels/d20.json';
import d21 from './levels/d21.json';
import d22 from './levels/d22.json';
import d23 from './levels/d23.json';
import d24 from './levels/d24.json';
import t24 from './levels/t24.json';
import d25 from './levels/d25.json';
import d26 from './levels/d26.json';
import d27 from './levels/d27.json';
import d28 from './levels/d28.json';
import d29 from './levels/d29.json';
import d30 from './levels/d30.json';
import d31 from './levels/d31.json';
import d32 from './levels/d32.json';
import d33 from './levels/d33.json';
import d34 from './levels/d34.json';
import d35 from './levels/d35.json';
import d36 from './levels/d36.json';
import t36 from './levels/t36.json';
import d37 from './levels/d37.json';
import d38 from './levels/d38.json';
import d39 from './levels/d39.json';
import d40 from './levels/d40.json';

/**
 * The campaign.
 *
 * Seven intro levels teach one idea each and end with the arcade's level-select: three
 * numbered exits letting a returning player start as deep as they can handle instead of
 * replaying the tutorial. After those, forty dungeon levels with a treasure room every
 * twelve, then the loop repeats with depth scaling applied to generator rates — there is
 * no ending, only a score.
 *
 * Generated by tools/mkcampaign.mjs, which validates every level for reachability
 * before writing it. Do not edit the JSON by hand; edit the recipe.
 */

/** The seven intro levels. Skipped entirely if you take a numbered exit. */
const INTRO_RAW: unknown[] = [i01, i02, i03, i04, i05, i06, i07];

/** The main loop: forty levels plus treasure rooms. */
const DUNGEON_RAW: unknown[] = [d01, d02, d03, d04, d05, d06, d07, d08, d09, d10, d11, d12, t12, d13, d14, d15, d16, d17, d18, d19, d20, d21, d22, d23, d24, t24, d25, d26, d27, d28, d29, d30, d31, d32, d33, d34, d35, d36, t36, d37, d38, d39, d40];

function check(raw: unknown, where: string): LevelData {
  const r = validateLevel(raw);
  if (!r.ok) throw new Error(`${where} failed validation:\n  ${r.errors.join('\n  ')}`);
  return r.data;
}

export const INTRO: readonly LevelData[] = INTRO_RAW.map((l, i) => check(l, `intro[${i}]`));
export const DUNGEONS: readonly LevelData[] = DUNGEON_RAW.map((l, i) => check(l, `dungeon[${i}]`));

/** Index 0..6 are the intro; everything after is the endless loop. */
export const CAMPAIGN: readonly LevelData[] = [...INTRO, ...DUNGEONS];

/**
 * Where the endless loop restarts once the authored levels run out.
 *
 * This matters: wrapping with plain modular arithmetic over the whole list would drop a
 * hardened player back into the tutorial, which is absurd. The loop skips the intro.
 */
export const LOOP_START = INTRO.length;

export { PROVING } from './proving';
