import { T } from './tuning';
import L01 from './layouts/L01.json';
import L02 from './layouts/L02.json';
import L03 from './layouts/L03.json';
import L04 from './layouts/L04.json';
import L05 from './layouts/L05.json';
import L06 from './layouts/L06.json';
import L07 from './layouts/L07.json';
import L08 from './layouts/L08.json';
import L09 from './layouts/L09.json';
import L10 from './layouts/L10.json';
import L11 from './layouts/L11.json';
import L12 from './layouts/L12.json';
import L13 from './layouts/L13.json';
import L14 from './layouts/L14.json';
import L15 from './layouts/L15.json';
import { validateLayout, type Layout } from '@/game/layout';

/**
 * The fifteen layouts.
 *
 * Generated by tools/mklayouts.mjs, which validates each one before writing it. Do not
 * edit the JSON by hand; edit the recipe. Validated again here at load, because a file
 * that is checked when it is written and never again is a file that drifts.
 */
const RAW: unknown[] = [L01, L02, L03, L04, L05, L06, L07, L08, L09, L10, L11, L12, L13, L14, L15];

export const LAYOUTS: readonly Layout[] = RAW.map((raw, i) => {
  const r = validateLayout(raw);
  if (!r.ok) throw new Error(`layout[${i}] failed validation:\n  ${r.errors.join('\n  ')}`);
  return r.data;
});

/**
 * Which layout a 1-based level number uses.
 *
 * After the fifteen run out the late ones repeat, rather than starting over from the
 * teaching levels — a player who has reached level 16 has demonstrated they do not need
 * "First Cut" again. Same reasoning as Bracer's LOOP_START.
 */
export function layoutFor(level: number): Layout {
  if (level <= LAYOUTS.length) return LAYOUTS[level - 1];
  const span = LAYOUTS.length - (T.CYCLE_FROM - 1);
  const into = (level - LAYOUTS.length - 1) % span;
  return LAYOUTS[T.CYCLE_FROM - 1 + into];
}

/**
 * How much faster enemies are at this level, as a multiplier.
 *
 * Capped, and the cap is the point: an enemy faster than the digger cannot be
 * disengaged from, so the game would stop being about routes and start being about luck.
 */
export function speedScale(level: number): number {
  return Math.min(T.RAMP_MAX, 1 + (level - 1) * T.RAMP_PER_LEVEL);
}
